// Datos de ejemplo para desarrollo/demo y para renderizar el dashboard sin un
// backend en marcha. Se usan cuando AGENTLENS_API_URL no está configurada.
import type { Span, TraceSummary } from "./types";

export const fixtureTraces: TraceSummary[] = [
  {
    trace_id: "9f2c1a7b3e",
    root_span_name: "invoke_agent support-bot",
    service_name: "support-agent",
    agent_id: "support-bot",
    start_time: "2026-06-25T10:00:00.000Z",
    duration_ms: 5.0,
    span_count: 2,
    error_count: 0,
    input_tokens: 120,
    output_tokens: 40,
  },
  {
    trace_id: "4b8d0c5f1a",
    root_span_name: "invoke_agent support-bot",
    service_name: "support-agent",
    agent_id: "support-bot",
    start_time: "2026-06-25T10:05:00.000Z",
    duration_ms: 2.0,
    span_count: 1,
    error_count: 1,
    input_tokens: 0,
    output_tokens: 0,
  },
  {
    trace_id: "1c6e9a2d7f",
    root_span_name: "invoke_agent biller",
    service_name: "billing-agent",
    agent_id: "biller",
    start_time: "2026-06-25T09:58:12.000Z",
    duration_ms: 18.4,
    span_count: 4,
    error_count: 0,
    input_tokens: 900,
    output_tokens: 320,
  },
];

export const fixtureSpans: Record<string, Span[]> = {
  "9f2c1a7b3e": [
    {
      span_id: "s1",
      parent_span_id: "",
      span_name: "invoke_agent support-bot",
      genai_operation: "invoke_agent",
      request_model: "",
      start_time: "2026-06-25T10:00:00.000Z",
      duration_ms: 5.0,
      status_code: "STATUS_CODE_OK",
      status_message: "",
      system_instructions: "Eres el asistente de soporte de ACME. Sé conciso.",
    },
    {
      span_id: "s2",
      parent_span_id: "s1",
      span_name: "chat gpt-4o",
      genai_operation: "chat",
      request_model: "gpt-4o",
      start_time: "2026-06-25T10:00:00.001Z",
      duration_ms: 3.0,
      status_code: "STATUS_CODE_OK",
      status_message: "",
      input_messages:
        '[{"role":"user","content":"¿Cuál es el estado de mi pedido 1234?"}]',
      output_messages:
        '[{"role":"assistant","content":"Tu pedido 1234 está en reparto y llega hoy."}]',
    },
  ],
  "4b8d0c5f1a": [
    {
      span_id: "s3",
      parent_span_id: "",
      span_name: "invoke_agent support-bot",
      genai_operation: "invoke_agent",
      request_model: "",
      start_time: "2026-06-25T10:05:00.000Z",
      duration_ms: 2.0,
      status_code: "STATUS_CODE_ERROR",
      status_message: "tool timeout",
    },
  ],
  "1c6e9a2d7f": [
    {
      span_id: "r1",
      parent_span_id: "",
      span_name: "invoke_agent biller",
      genai_operation: "invoke_agent",
      request_model: "",
      start_time: "2026-06-25T09:58:12.000Z",
      duration_ms: 18.4,
      status_code: "STATUS_CODE_OK",
      status_message: "",
    },
    {
      span_id: "r2",
      parent_span_id: "r1",
      span_name: "chat claude-sonnet-4-6",
      genai_operation: "chat",
      request_model: "claude-sonnet-4-6",
      start_time: "2026-06-25T09:58:12.002Z",
      duration_ms: 9.1,
      status_code: "STATUS_CODE_OK",
      status_message: "",
    },
    {
      span_id: "r3",
      parent_span_id: "r1",
      span_name: "execute_tool fetch_invoice",
      genai_operation: "execute_tool",
      request_model: "",
      start_time: "2026-06-25T09:58:12.012Z",
      duration_ms: 5.0,
      status_code: "STATUS_CODE_OK",
      status_message: "",
    },
    {
      span_id: "r4",
      parent_span_id: "r1",
      span_name: "chat claude-sonnet-4-6",
      genai_operation: "chat",
      request_model: "claude-sonnet-4-6",
      start_time: "2026-06-25T09:58:12.018Z",
      duration_ms: 0.4,
      status_code: "STATUS_CODE_OK",
      status_message: "",
    },
  ],
};
